# Generated by Django 5.2 on 2025-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title_name', models.CharField(max_length=100)),
                ('has_passport', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('notes', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
