# Generated by Django 5.2 on 2025-04-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfproviderapp', '0002_country_department_employee_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='drfproviderapp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='drfproviderapp.department'),
        ),
    ]
