# Generated by Django 5.2 on 2025-04-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfproviderapp', '0003_alter_employee_country_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='drfproviderapp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='drfproviderapp.department'),
        ),
    ]
