# Generated by Django 5.2 on 2025-05-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfproviderapp', '0004_alter_employee_country_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='drfproviderapp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Departments', to='drfproviderapp.department'),
        ),
    ]
